version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.development
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/.venv
    command:
      [
        "poetry",
        "run",
        "uvicorn",
        "app.app:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload",
      ]
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
